layout: {zmk_keyboard: corne_c}
layers:
  '0':
  - TAB
  - ''''
  - ','
  - .
  - P
  - Y
  - F
  - G
  - C
  - R
  - L
  - /
  - LEFT CONTROL
  - A
  - O
  - E
  - U
  - I
  - D
  - H
  - T
  - N
  - S
  - '-'
  - LEFT SHIFT
  - ;
  - Q
  - J
  - K
  - X
  - B
  - M
  - W
  - V
  - Z
  - '='
  - LEFT ALT
  - ENTER
  - {t: (, h: '1'}
  - {t: ), h: '2'}
  - SPACE
  - LEFT WIN
  '1':
  - ESC
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - BSPC
  - '`'
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - VOLUME UP
  - UP ARROW
  - VOLUME DOWN
  - '~'
  - AL FILE BROWSER
  - AL WWW
  - COPY
  - PASTE
  - PRINTSCREEN
  - PREVIOUS
  - PLAY PAUSE
  - NEXT
  - LEFT ARROW
  - DOWN ARROW
  - RIGHT ARROW
  - ''
  - ''
  - {type: held}
  - ''
  - '['
  - ']'
  '2':
  - TAB
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - '&mkp MCLK'
  - DELETE
  - \
  - '&macro0'
  - '&macro1'
  - '&macro2'
  - '&macro3'
  - '&macro4'
  - ''
  - ''
  - '&msc SCRL_UP'
  - '&mkp LCLK'
  - '&mmv MOVE_UP'
  - '&mkp RCLK'
  - '|'
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - BT CLR
  - BT CLR ALL
  - '&msc SCRL_DOWN'
  - '&mmv MOVE_LEFT'
  - '&mmv MOVE_DOWN'
  - '&mmv MOVE_RIGHT'
  - '{'
  - '}'
  - ''
  - {type: held}
  - '&bootloader'
  - ''
