layout: {zmk_keyboard: corne_c}
layers:
  '0':
  - ESCAPE
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - BACKSPACE
  - LSHFT
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - DELETE
  - LEFT ALT
  - {t: LEFT GUI, h: '3'}
  - {t: SPACE, h: '1'}
  - ENTER
  - '2'
  - RIGHT WIN
  '1':
  - \
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - BSPC
  - LSHFT
  - A
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '['
  - ']'
  - '|'
  - LCTRL
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ','
  - .
  - '-'
  - '='
  - LEFT ALT
  - LEFT GUI
  - {t: SPACE, type: held}
  - RET
  - RIGHT ALT
  - RIGHT GUI
  '2':
  - TAB
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - (
  - )
  - BSPC
  - LCTRL
  - ''
  - ''
  - ''
  - ''
  - ''
  - '-'
  - '='
  - '['
  - ']'
  - \
  - '`'
  - LSHFT
  - ''
  - ''
  - ''
  - ''
  - ''
  - _
  - +
  - '{'
  - '}'
  - '|'
  - '~'
  - LEFT GUI
  - LSHFT
  - SPACE
  - ENTER
  - {t: RIGHT COMMAND, type: held}
  - RIGHT GUI
  '3':
  - '&sys_reset'
  - ''
  - ''
  - ''
  - ''
  - ''
  - KP 7
  - KP 8
  - KP 9
  - ''
  - ''
  - ''
  - LSHFT
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - KP 4
  - KP 5
  - KP 6
  - ''
  - UP
  - ''
  - LCTRL
  - BT CLR
  - ''
  - ''
  - ''
  - BT CLR ALL
  - KP 1
  - KP 2
  - KP 3
  - LEFT
  - DOWN
  - RIGHT
  - LEFT ALT
  - {t: LEFT GUI, type: held}
  - SPACE
  - '0'
  - '0'
  - KP DOT
